const today = new Date();

function daysFromNow(days) {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days) {
  const d = new Date(today);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

const DUMMY_OPPORTUNITIES = [
  {
    noticeId: 'DUMMY-001',
    title: 'Office Supplies and Stationery — Blanket Purchase Agreement',
    agency: 'DEPT OF VETERANS AFFAIRS',
    subAgency: 'Veterans Benefits Administration',
    naicsCode: '424120',
    opportunityType: 'o',
    setAsideType: 'SBA',
    setAsideDescription: 'Small Business Set-Aside',
    postedDate: daysAgo(3),
    responseDeadline: daysFromNow(21),
    description: 'The Department of Veterans Affairs requires a vendor to supply office supplies and stationery products for 12 regional offices. Items include paper, pens, folders, binders, and general office consumables. Estimated annual spend $180,000. Delivery within 5 business days of order. Small business set-aside.',
    uiLink: 'https://sam.gov',
    valueMin: 150000,
    valueMax: 220000,
    valueLabel: '$150,000 - $220,000',
    valueSource: 'description_range',
    score: 95,
    reasons: ['NAICS code match', 'Set-aside certification match', 'Good lead time'],
  },
  {
    noticeId: 'DUMMY-002',
    title: 'Copy Paper and Printer Supplies — Annual Contract',
    agency: 'GENERAL SERVICES ADMINISTRATION',
    subAgency: 'Federal Acquisition Service',
    naicsCode: '424120',
    opportunityType: 'k',
    setAsideType: 'SBA',
    setAsideDescription: 'Small Business Set-Aside',
    postedDate: daysAgo(5),
    responseDeadline: daysFromNow(18),
    description: 'GSA requires a supplier of copy paper (8.5x11 and 11x17), printer toner cartridges, and ink supplies for federal offices in the DC metro area. Estimated 500 cases of paper per month. FOB destination required. Annual contract with 2 option years.',
    uiLink: 'https://sam.gov',
    valueMin: 200000,
    valueMax: 400000,
    valueLabel: '$200,000 - $400,000',
    valueSource: 'description_range',
    score: 92,
    reasons: ['NAICS code match', 'Set-aside certification match', 'Good lead time'],
  },
  {
    noticeId: 'DUMMY-003',
    title: 'Janitorial and Cleaning Supplies — Sources Sought',
    agency: 'DEPT OF DEFENSE',
    subAgency: 'Defense Logistics Agency',
    naicsCode: '424690',
    opportunityType: 'r',
    setAsideType: 'SBA',
    setAsideDescription: 'Small Business Set-Aside',
    postedDate: daysAgo(2),
    responseDeadline: daysFromNow(14),
    description: 'DLA is conducting market research for a supply contract covering janitorial and cleaning products for military installations. Products include disinfectants, paper towels, trash bags, and cleaning chemicals. Anticipated IDIQ vehicle, 5-year ordering period.',
    uiLink: 'https://sam.gov',
    valueMin: 300000,
    valueMax: 1200000,
    valueLabel: '$300,000 - $1,200,000',
    valueSource: 'description_range',
    score: 78,
    reasons: ['Related NAICS sector', 'Sources Sought — early intel', 'Good lead time'],
  },
  {
    noticeId: 'DUMMY-004',
    title: 'Office Furniture and Seating — GSA Schedule Order',
    agency: 'DEPT OF HOMELAND SECURITY',
    subAgency: 'FEMA',
    naicsCode: '423210',
    opportunityType: 'o',
    setAsideType: 'WOSB',
    setAsideDescription: 'Women-Owned Small Business',
    postedDate: daysAgo(4),
    responseDeadline: daysFromNow(12),
    description: 'FEMA requires office furniture for a new regional coordination center. Items include 120 ergonomic desk chairs, 40 adjustable-height desks, conference room tables, and filing cabinets. Delivery and installation required. Brand or approved equal acceptable.',
    uiLink: 'https://sam.gov',
    valueMin: 180000,
    valueMax: 320000,
    valueLabel: '$180,000 - $320,000',
    valueSource: 'description_range',
    score: 74,
    reasons: ['Related NAICS sector', 'Good lead time'],
  },
  {
    noticeId: 'DUMMY-005',
    title: 'Medical Supplies and Consumables — Annual BPA',
    agency: 'DEPT OF VETERANS AFFAIRS',
    subAgency: 'Veterans Health Administration',
    naicsCode: '423450',
    opportunityType: 'o',
    setAsideType: 'SDVOSBC',
    setAsideDescription: 'Service-Disabled Veteran-Owned Small Business',
    postedDate: daysAgo(6),
    responseDeadline: daysFromNow(25),
    description: 'VA Healthcare System requires a blanket purchase agreement for medical consumables including gloves, syringes, bandages, and examination supplies for 3 VA medical centers. Estimated annual spend $520,000. Vendor must be FDA-registered distributor.',
    uiLink: 'https://sam.gov',
    valueMin: 400000,
    valueMax: 650000,
    valueLabel: '$400,000 - $650,000',
    valueSource: 'description_range',
    score: 68,
    reasons: ['Related NAICS sector', 'Good lead time'],
  },
  {
    noticeId: 'DUMMY-006',
    title: 'Breakroom and Kitchen Supplies — Pre-Solicitation',
    agency: 'DEPT OF JUSTICE',
    subAgency: 'FBI',
    naicsCode: '424490',
    opportunityType: 'p',
    setAsideType: 'SBA',
    setAsideDescription: 'Small Business Set-Aside',
    postedDate: daysAgo(1),
    responseDeadline: daysFromNow(30),
    description: 'The FBI anticipates issuing a solicitation for breakroom and kitchen supplies including coffee, beverages, paper plates, utensils, and food service items for headquarters and field offices. Annual spend estimated at $95,000. Delivery weekly or bi-weekly to multiple locations.',
    uiLink: 'https://sam.gov',
    valueMin: 80000,
    valueMax: 120000,
    valueLabel: '$80,000 - $120,000',
    valueSource: 'description_range',
    score: 71,
    reasons: ['Related NAICS sector', 'Good lead time'],
  },
  {
    noticeId: 'DUMMY-007',
    title: 'Personal Protective Equipment (PPE) Supply Contract',
    agency: 'DEPT OF LABOR',
    subAgency: 'OSHA',
    naicsCode: '423990',
    opportunityType: 'o',
    setAsideType: 'HZC',
    setAsideDescription: 'HUBZone Small Business Set-Aside',
    postedDate: daysAgo(7),
    responseDeadline: daysFromNow(16),
    description: 'OSHA requires a supplier of personal protective equipment including hard hats, safety vests, gloves, eye protection, and respirators for field inspectors nationwide. Items must meet ANSI standards. Indefinite delivery contract, 1 year base plus 4 options.',
    uiLink: 'https://sam.gov',
    valueMin: 90000,
    valueMax: 250000,
    valueLabel: '$90,000 - $250,000',
    valueSource: 'description_range',
    score: 65,
    reasons: ['Good lead time'],
  },
  {
    noticeId: 'DUMMY-008',
    title: 'Tactical and Outdoor Equipment Supply — Sources Sought',
    agency: 'DEPT OF DEFENSE',
    subAgency: 'US Army',
    naicsCode: '423990',
    opportunityType: 'r',
    setAsideType: 'SBA',
    setAsideDescription: 'Small Business Set-Aside',
    postedDate: daysAgo(3),
    responseDeadline: daysFromNow(10),
    description: 'US Army is conducting market research for a supplier of tactical backpacks, hydration systems, and field equipment for training units. Estimated annual quantity: 2,000 backpacks at $85-120 each, plus accessories. TAA compliance required.',
    uiLink: 'https://sam.gov',
    valueMin: 180000,
    valueMax: 280000,
    valueLabel: '$180,000 - $280,000',
    valueSource: 'description_range',
    score: 62,
    reasons: ['Sources Sought — early intel'],
  },
  {
    noticeId: 'DUMMY-009',
    title: 'IT Hardware and Peripherals — Blanket Purchase Agreement',
    agency: 'NASA',
    subAgency: 'Goddard Space Flight Center',
    naicsCode: '423430',
    opportunityType: 'o',
    setAsideType: 'SBA',
    setAsideDescription: 'Small Business Set-Aside',
    postedDate: daysAgo(8),
    responseDeadline: daysFromNow(20),
    description: 'NASA Goddard requires a BPA for IT peripherals including monitors, keyboards, mice, USB hubs, webcams, and cables. Estimated annual spend $140,000. Must be authorized reseller of major brands. TAA-compliant products only. Next-day delivery to campus required.',
    uiLink: 'https://sam.gov',
    valueMin: 100000,
    valueMax: 180000,
    valueLabel: '$100,000 - $180,000',
    valueSource: 'description_range',
    score: 58,
    reasons: ['Good lead time'],
  },
  {
    noticeId: 'DUMMY-010',
    title: 'Uniforms and Workwear Supply — Annual Contract',
    agency: 'DEPT OF TRANSPORTATION',
    subAgency: 'Federal Aviation Administration',
    naicsCode: '315990',
    opportunityType: 'o',
    setAsideType: '8AN',
    setAsideDescription: '8(a) Set-Aside',
    postedDate: daysAgo(10),
    responseDeadline: daysFromNow(8),
    description: 'FAA requires a supplier of uniforms and workwear for maintenance and operations staff at 15 airports. Items include work shirts, pants, jackets, and safety vests with FAA logo embroidery. Estimated 3,000 units annually. GSA Schedule preferred but open market acceptable.',
    uiLink: 'https://sam.gov',
    valueMin: 120000,
    valueMax: 200000,
    valueLabel: '$120,000 - $200,000',
    valueSource: 'description_range',
    score: 55,
    reasons: [],
  },
];

module.exports = { DUMMY_OPPORTUNITIES };
